# Generated by Django 5.2.8 on 2025-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the location')),
                ('description', models.TextField(blank=True)),
                ('cuisine', models.CharField(default='Vegetarian', max_length=100)),
                ('price_range', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$$', max_length=50)),
            ],
            options={
                'verbose_name': 'Lunch Spot',
                'verbose_name_plural': 'Lunch Spots',
            },
        ),
        migrations.CreateModel(
            name='Pandit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the location')),
                ('description', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(default=5)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Vedic Rituals, Katha', max_length=100)),
            ],
            options={
                'verbose_name': 'Pandit',
                'verbose_name_plural': 'Pandits',
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, help_text='URL to an image of the location')),
                ('description', models.TextField(blank=True)),
                ('deity', models.CharField(blank=True, max_length=100)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Temple',
                'verbose_name_plural': 'Temples',
            },
        ),
    ]
