# Generated by Django 5.1.6 on 2025-11-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pandit',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pandit',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='pandit',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image of the pandit'),
        ),
    ]
